# Generated by Django 3.1.7 on 2021-06-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField(blank=True, max_length=100, null=True)),
                ('part_no', models.TextField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('cross_part', models.TextField(blank=True, max_length=100, null=True)),
                ('price', models.TextField(blank=True, max_length=100, null=True)),
                ('url', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
