# Generated by Django 3.1.7 on 2021-06-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_table',
            name='part_no_form',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
