# Generated by Django 3.1.7 on 2021-06-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_main_table_part_no_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_table',
            name='supplier',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
